name: Fetch SMARD data

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes (UTC)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # Option A: install exactly what you need (fastest if small)
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install requests pandas urllib3

      - name: Run script
        run: python fetch_power.py
        # working-directory: path/to/dir  # if it's not in repo root
