name: Incremental SMARD

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes UTC
  workflow_dispatch:

jobs:
  incremental:
    runs-on: ubuntu-latest
    concurrency:
      group: smard-incremental
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }
      - run: pip install -r requirements.txt
      - name: Run incremental
        env:
          BUCKET_URL: ${{ secrets.BUCKET_URL }}
          FILTER_ID: ${{ secrets.FILTER_ID }}
          REGION_CODE: DE
          HWM_URL: ${{ secrets.HWM_URL }}
          OVERLAP_HOURS: "4"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: python incremental.py
